version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: shop-api-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: shop_db
      POSTGRES_USER: shop_user
      POSTGRES_PASSWORD: shop_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shop-network

volumes:
  postgres_data:

networks:
  shop-network:
    driver: bridge